NAVIGATOR_KEY_LIST = ['appCodeName', 'appName', 'appVersion', 'canvas', 'colorDepth',
			'cookieEnabled', 'doNotTrack', 'fonts',
			'hardwareConcurrency', 'height', 'javaEnabled', 
			'language', 'localStorage', 'mimetypes', 'onLine',
			'platform', 'plugins', 'product', 'timezone', 'userAgent', 'vendor','webGLRenderer', 'webGLVendor','width']


NAVIGATOR_KEY_SCORE_MAP = {"appCodeName":0,
							"appName":0,
							"appVersion":0,
							"canvas":0.475,
							"colorDepth":0,
							"cookieEnabled":0.016,
							"doNotTrack":0.057,
							"fonts":0.548,
							"hardwareConcurrency":0,
							"height":0.131,
							"javaEnabled":0,
							"language":0,
							"localStorage":0.023,
							"mimetypes":0,
							"onLine":0,
							"platform":0.110,
							"plugins":0.718,
							"product":0,
							"timezone":0.200,
							"userAgent":0.550,
							"vendor":0,
							"webGLRenderer":0.205,
							"webGLVendor":0.125,
							"width":0.131}


MOBILE_WEB_NAVIGATOR_KEY_LIST = ['appCodeName', 'appName', 'appVersion', 'canvas', 'colorDepth',
			'cookieEnabled', 'doNotTrack', 'fonts',
			'hardwareConcurrency', 'height', 'javaEnabled', 
			'language', 'localStorage', 'mimetypes', 'onLine',
			'platform', 'plugins', 'product', 'timezone', 'userAgent', 'vendor','webGLRenderer', 'webGLVendor','width']


MOBILE_WEB_NAVIGATOR_KEY_SCORE_MAP = {"appCodeName":0,
							"appName":0,
							"appVersion":0,
							"canvas":0.512,
							"colorDepth":0,
							"cookieEnabled":0.011,
							"doNotTrack":0.058,
							"fonts":0.033,
							"hardwareConcurrency":0,
							"height":0.183,
							"javaEnabled":0,
							"language":0,
							"localStorage":0.036,
							"mimetypes":0,
							"onLine":0,
							"platform":0.162,
							"plugins":0.081,
							"product":0,
							"timezone":0.245,
							"userAgent":0.741,
							"vendor":0,
							"webGLRenderer":0.165,
							"webGLVendor":0.131,
							"width":0.183}

